wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742234477.0
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 13
      - 23
      4: 3.11.4
      5: 0.16.5
      8:
      - 5
      13: darwin-arm64
